#---------------------------------
#use space instead of tab in this file
#---------------------------------
#
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

#global settings
#```````````````````
#set sitesource
##source: DIR
#
#site destination
##destination: DIR
#
#safe: off customized plugin
#safe: BOOL
#
#exclude files/folders when transform
#exclude: [DIR, FILE, ...]
#
#include files by force when transform
#include: [DIR, FILE...]
#
#keep_files: [DIR ...]
#
#timezone: TIMEZONE
#
#encoding: utf-8 default
#
#compile settings
#````````````````
#regeneration automatively
#(with cmd) -w --watch
#
#configuration several
#(with cmd) --config FILE...
#
# --drafts
#
#environment:JEKYLL_ENV=production
#
#use future date to release articles
# future: BOOL
#
# LSI = latency semantics index
#lsi:BOOL
#
#limit Posts quantaty
#limit_posts:NUM
#
#force polling
#(with cmd) --force_polling
#
#verbose output (with cmd) -V --verbose
#
#silence output (with cmd) -q --quiet
#
#incremental build: incremental: BOOL
#
#liquid profiler compose a doc for performance
#improvememt: profile: BOOL
#
#
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
# defaults:
#   -
#    scope:
#      path:""
#      type:"posts"/pages/drafts
#    values:
#      layout:"default"
